

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/namdoon
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true